services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mysql
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.19
    environment:
      - MYSQL_DATABASE=api
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: {}